services:

  postgres:
    image: postgres:16
    container_name: dw_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: data_warehouse_economia
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow-init:
    build: .
    container_name: dw_airflow_init
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:12345@postgres:5432/data_warehouse_economia
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: admin
      _AIRFLOW_WWW_USER_PASSWORD: admin
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create \
          --username admin \
          --firstname Julian \
          --lastname Admin \
          --role Admin \
          --email admin@example.com \
          --password admin || true
        echo "Airflow init completado"

  airflow-webserver:
    build: .
    container_name: dw_airflow_webserver
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:12345@postgres:5432/data_warehouse_economia
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mi_clave_secreta_airflow_2026"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: data_warehouse_economia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
    ports:
      - "8080:8080"
    command: airflow webserver

  airflow-scheduler:
    build: .
    container_name: dw_airflow_scheduler
    depends_on:
      postgres:
        condition: service_healthy
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:12345@postgres:5432/data_warehouse_economia
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__SECRET_KEY: "mi_clave_secreta_airflow_2026"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: "5432"
      POSTGRES_DB: data_warehouse_economia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
    command: airflow scheduler

  superset:
    image: apache/superset:latest
    container_name: dw_superset
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SUPERSET_SECRET_KEY: "mi_clave_secreta_superset_2026"
    ports:
      - "8088:8088"
    volumes:
      - superset_data:/app/superset_home

volumes:
  postgres_data:
  superset_data: